Pokedex app
SofiaDavidov/pokedex-stylable pull request #1
Opened 2022-04-03 14:28 UTC by SofiaDavidov

2022-04-05 07:43 UTC, eifr reviewed
add `.DS_Store` to `.gitignore`

2022-04-05 08:18 UTC, eifr requested changes
looks great! but way too long and many unrelated stuff...
please separate to multiple pr.. at least remove all configs and settings out, add `dist` (make sure webpack bundles into it)

2022-04-05 08:18 UTC, eifr commented on src/api.ts
> +    return (await res.json()) as { results: PokemonListItem[] };
[checkout this](https://jakearchibald.com/2017/await-vs-return-vs-return-await/#:~:text=Note%3A%20Outside%20of%20try/catch%20blocks%2C%20return%20await%20is%20redundant.%20There%27s%20even%20an%20ESLint%20rule%20to%20detect%20it%2C%20but%20it%20allows%20it%20in%20try/catch.)

2022-04-05 08:18 UTC, eifr commented on src/app.tsx
> +/* eslint-disable @typescript-eslint/no-unsafe-assignment */
why?

2022-04-05 08:18 UTC, eifr commented on src/components/card-list/CardList.tsx
> +import type { PokemonInfo } from '../../types';
`import type` should be last

2022-04-05 08:18 UTC, eifr commented on src/components/card-list/CardList.tsx
> +const CardList: React.FC = () => {
```suggestion
const CardList: React.VFC = () => {
```

2022-04-05 12:00 UTC, SofiaDavidov commented on .mocharc.js
> +module.exports = {
Done

2022-04-05 12:01 UTC, SofiaDavidov commented on package.json
> +    "test:spec": "mocha-play \"**/*.spec.tsx\""
Yes, for now...

2022-04-06 06:32 UTC, SofiaDavidov commented on src/components/pokedex/Top.tsx
> +const Top = () => {
Add return type

2022-04-06 06:32 UTC, SofiaDavidov commented on src/components/pokemon-info/Info.tsx
> +const Info = () => {
Add return type

2022-04-06 06:32 UTC, SofiaDavidov commented on src/components/pokemon-info/details-section/details-views/detailsViews.st.css
> +    /* background-color: var(--typeColor); */
remove comment

2022-04-06 06:32 UTC, SofiaDavidov commented on src/components/pokemon-info/details-section/details-views/detailsViews.st.css
> +    /* justify-content: center; */
remove

2022-04-06 06:32 UTC, SofiaDavidov commented on src/components/pokemon-info/details-section/details-views/pokemon-overview/PokemonOverview.tsx
> +const Type = ({ type }: { type: PokemonTypes }) => {
Add return type

2022-04-06 06:32 UTC, SofiaDavidov commented on src/components/pokemon-info/details-section/details-views/pokemon-overview/PokemonOverview.tsx
> +const Type = ({ type }: { type: PokemonTypes }) => {
and props interface

2022-04-06 06:32 UTC, SofiaDavidov commented on src/components/pokemon-info/details-section/details-views/pokemon-overview/PokemonOverview.tsx
> +const KeyVal = ({
Return type + interface

2022-04-06 06:32 UTC, SofiaDavidov commented on src/components/pokemon-info/details-section/details-views/pokemon-stats/PokemonStats.tsx
> +                                [vars.typeColor]: pokemonTypeColors[types[0].type.name],
const [pokemonType] = types;

2022-04-06 06:32 UTC, SofiaDavidov commented on src/components/tabs/tabs.st.css
> +    border-bottom: 2px solid #DFDFDF;
Add vars(?) for #DFDFDF

2022-04-06 06:32 UTC, SofiaDavidov commented on src/components/pokemon-info/details-section/DetailsWrapper.tsx
> +    const pokemonType = types?.[0].type.name ?? DEFAULT_TYPE;
const [type] = types;

2022-04-06 06:32 UTC, SofiaDavidov commented on src/components/pokemon-info/details-section/details-views/detailsViews.spec.tsx
> +    expect(typeCapsules[1].textContent).to.include(pokemon.types[1].type.name);
pokemon.types.forEach

2022-04-07 09:26 UTC, eifr requested changes
extract e2e to own PR

2022-04-07 09:26 UTC, eifr commented on test/e2e.test.ts
> +        expect(pokemonName?.toLowerCase()).to.not.contain('bulbasaur');
check of image

2022-04-07 09:26 UTC, eifr commented on test/e2e.test.ts
> +        await firstPokemonCard.waitFor();
remove

2022-04-07 09:26 UTC, eifr commented on test/e2e.test.ts
> +        expect(firstCardNameText?.toLocaleLowerCase()).to.equal('bulbasaur');
extract to var

2022-04-07 09:26 UTC, eifr commented on test/e2e.test.ts
> +        await searchTab.waitFor();
remove

2022-04-07 09:26 UTC, eifr commented on test/e2e.test.ts
> +        await selectedPokemonInfo.waitFor({ timeout: 3000 });
waitFor pikatchu

2022-04-07 09:26 UTC, eifr commented on test/e2e.test.ts
> +        await searchInput.fill('pikachu');
export to var

2022-04-12 10:01 UTC, eifr requested changes

2022-04-12 10:01 UTC, eifr commented on src/components/card-list/CardList.tsx
> +const NUM_OF_CARDS = 20;
add as props

2022-04-13 20:10 UTC, eifr commented on src/components/card-list/card/Card.tsx
> +            className={st(classes.root, {disabled: onClick == null})}
```suggestion
            className={st(classes.root, {disabled: !onClick})}
```

2022-04-13 20:10 UTC, eifr commented on src/components/card-list/card/card.spec.tsx
> +let container: Element;
wrap all with `describe`

2022-04-13 20:15 UTC, eifr commented on src/components/card-list/CardList.tsx
> +        if (allPokemons === null || allPokemons.length === 0) return;
```suggestion
        if (allPokemons === null || allPokemons.length === 0) {
           return;
        }
```

2022-04-13 20:15 UTC, eifr commented on src/components/card-list/card-list.st.css
> +    width: 400px
why `height` and `width`? should this component choose its sizes? (IMO it can be relative to parent/container)

2022-04-13 20:21 UTC, eifr requested changes

2022-04-13 20:21 UTC, eifr commented on src/components/pokedex/Pokedex.tsx
> +import type {
`import type` should be last

2022-04-13 20:21 UTC, eifr commented on src/components/pokedex/Top.tsx
> +const Top = () => {
type?

2022-04-13 20:21 UTC, eifr commented on src/components/pokedex/pokedexContainer.st.css
> +    background-color: var(--color);
default value?

2022-04-13 20:21 UTC, eifr commented on src/components/pokemon-info/buttons-section/buttonsSection.spec.tsx
> +let container: Element;
wrap with `describe`

2022-04-13 20:21 UTC, eifr commented on src/components/search-input/Search.tsx
> +                console.log(e);
?

2022-04-17 08:09 UTC, eifr commented on src/components/card-list/CardList.tsx
> +    function loadMore() {
```suggestion
    function loadMoreHandler() {
```

(add `useCallback`)

2022-04-17 08:09 UTC, eifr commented on src/components/card-list/card/Card.tsx
> +import type { PokemonTypes } from '../../../types';
:rocket:

2022-04-17 08:09 UTC, eifr commented on src/components/card-list/card/card.st.css
> +    background-color: #E54222;
```suggestion
    --typeColor: #E54222;
```

2022-04-17 08:09 UTC, eifr commented on src/components/card-list/card/card.st.css
> +}
eof

2022-04-17 08:09 UTC, eifr commented on src/components/pokedex/pokedexContainer.st.css
> +    height: 100%;
```suggestion
flex:1
```

2022-04-17 08:10 UTC, eifr commented
fix description + commit name

2022-04-18 08:20 UTC, eifr commented
rename image file to be svg/png (whatever the image is)

2022-04-18 10:19 UTC, eifr commented on src/components/pokemon-info/Info.tsx
> +const Info: React.VFC = memo(() => {
remove `VFC`

2022-04-18 10:19 UTC, eifr commented on src/components/pokemon-info/Info.tsx
> +enum ViewsType {
change to array

2022-04-18 10:19 UTC, eifr commented on src/components/pokemon-info/details-section/DetailsWrapper.tsx
> +    viewToDisplay: ({ selectedPokemon }: { selectedPokemon: PokemonInfo }) => JSX.Element;
`ViewToDisplay: React.VFC<{selectedPokemon: PokemonInfo}>`

2022-04-18 10:19 UTC, eifr commented on src/components/pokemon-info/details-section/DetailsWrapper.tsx
> +    selectedPokemon: PokemonInfo | null;
selectedPokemon?: PokemonInfo;

2022-04-18 10:19 UTC, eifr commented on src/components/pokemon-info/details-section/detailsWrapper.spec.tsx
> +beforeEach(() => {
describe

2022-04-18 10:19 UTC, eifr commented on src/components/pokemon-info/details-section/detailsWrapper.spec.tsx
> +it('render DetailsSection with selected pokemon', () => {
what are you expecting to happen?

2022-04-19 14:10 UTC, SofiaDavidov commented on src/components/pokemon-info/details-section/details-views/detailsViews.spec.tsx
> +            if (statText !== null) {
hafuch

2022-04-19 14:19 UTC, merged